#!/usr/bin/env node
/**
 * Sync global rules from `.ai/rules/*.md` to:
 * - Cursor: `.cursor/rules/global_standards/*.mdc`
 * - Claude: repo-root `CLAUDE.md`
 *
 * Usage: node .ai/rules/sync-rules.mjs
 *        npm run sync:rules
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const RULES_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(RULES_DIR, '../..')
const CURSOR_RULES_DIR = path.join(REPO_ROOT, '.cursor', 'rules', 'global_standards')
const CLAUDE_MD = path.join(REPO_ROOT, 'CLAUDE.md')

const CLAUDE_TITLE = 'Envision AI-SDLC — Project Rules'

/** @type {ReadonlyArray<{ id: string; file: string; title: string; description: string }>} */
const RULES = [
  {
    id: 'product_context',
    file: 'product_context.md',
    title: 'Product Context',
    description: 'High-level business vision, target users, and UX requirements for all features',
  },
  {
    id: 'tech_context',
    file: 'tech_context.md',
    title: 'Tech Context',
    description: 'Tech stack, runtime environments, and local setup commands',
  },
  {
    id: 'system_patterns',
    file: 'system_patterns.md',
    title: 'System Patterns',
    description: 'System architecture, folder structure, naming conventions, and constraints',
  },
  {
    id: 'design_system',
    file: 'design_system.md',
    title: 'Design System',
    description: 'Design system — tokens live in repo-root design-system.json',
  },
]

/**
 * @param {string} body
 * @param {string} title
 * @returns {string}
 */
function bodyForClaudeSection(body, title) {
  const trimmed = body.trimStart()
  const h1Match = trimmed.match(/^# (.+)\r?\n\r?\n?/)
  if (h1Match && h1Match[1].trim() === title) {
    return trimmed.slice(h1Match[0].length).trimStart()
  }
  return trimmed.replace(/^# /m, '## ')
}

/**
 * @param {string} description
 * @param {string} body
 * @returns {string}
 */
function toCursorMdc(description, body) {
  return `---\ndescription: ${description}\nalwaysApply: true\n---\n\n${body.trimEnd()}\n`
}

function main() {
  /** @type {Array<{ title: string; body: string }>} */
  const sections = []

  for (const rule of RULES) {
    const sourcePath = path.join(RULES_DIR, rule.file)
    if (!fs.existsSync(sourcePath)) {
      console.error(`sync-rules: missing source file: ${sourcePath}`)
      process.exit(1)
    }

    const body = fs.readFileSync(sourcePath, 'utf8').trimEnd()

    fs.mkdirSync(CURSOR_RULES_DIR, { recursive: true })
    const cursorPath = path.join(CURSOR_RULES_DIR, `${rule.id}.mdc`)
    fs.writeFileSync(cursorPath, toCursorMdc(rule.description, body), 'utf8')
    console.log(`wrote ${path.relative(REPO_ROOT, cursorPath)}`)

    sections.push({ title: rule.title, body })
  }

  const claudeBody = [
    `# ${CLAUDE_TITLE}`,
    '',
    '> Generated by `.ai/rules/sync-rules.mjs`. Edit sources under `.ai/rules/`, then re-run the sync.',
    '',
    ...sections.flatMap(({ title, body }) => [
      `## ${title}`,
      '',
      bodyForClaudeSection(body, title),
      '',
    ]),
  ]
    .join('\n')
    .trimEnd()
    .concat('\n')

  fs.writeFileSync(CLAUDE_MD, claudeBody, 'utf8')
  console.log(`wrote ${path.relative(REPO_ROOT, CLAUDE_MD)}`)
}

main()
